#!/usr/bin/env bash
#
# Builds the Frege compiler from a pinned `master` commit that contains the
# automated FFI feature (PR #400, https://github.com/Frege/frege/pull/400) and
# copies the resulting jar to libs/frege-compiler-snapshot.jar.
#
# The produced fregec.jar bundles BOTH the compiler and the runtime, so it is
# the only Frege jar froid needs (it is on the compile classpath and the app
# runtime classpath).
#
# Requirements (NOT satisfied by a stock macOS box with only JDK 25/26):
#   - A JDK in the 8..17 range (the Makefile compiles at -source/-target 1.8;
#     javac 21+ has dropped support for source 8). JDK 17 is recommended.
#   - GNU make, curl, and the `jar` tool.
#   - byacc is NOT required: the grammar (frege/compiler/grammar/Frege.fr) ships
#     pre-generated and is only regenerated by the `make rebuild` target.
#
# Usage:
#   tools/build-frege-snapshot.sh            # builds into ./libs
#   JAVA_HOME=/path/to/jdk17 tools/build-frege-snapshot.sh
#
set -euo pipefail

# Pinned Frege master HEAD that includes the auto-FFI merge (#400).
FREGE_COMMIT="067cad057385d36134812bde3fc1b453e5274855"
# Released compiler used to bootstrap the source build (from Frege's .travis.yml).
BOOTSTRAP_JAR_URL="https://github.com/Frege/frege/releases/download/3.25alpha/frege3.25.84.jar"

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
dest="$repo_root/libs/frege-compiler-snapshot.jar"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "==> Using java: $(command -v java)"
java -version
case "$(java -version 2>&1 | head -n1)" in
  *\"2[0-9].*|*\"1[89].*|*\"17.*) : ;;  # 17/18/19 ok-ish; 20+ likely rejects -source 8
esac

echo "==> Cloning Frege @ $FREGE_COMMIT"
git clone --quiet https://github.com/Frege/frege.git "$work/frege"
git -C "$work/frege" checkout --quiet "$FREGE_COMMIT"

# Sanity: confirm the auto-FFI example is present (proves #400 is in the tree).
test -f "$work/frege/examples/CommandLineClockAutoFFI.fr" \
  || { echo "ERROR: auto-FFI example missing — wrong commit?" >&2; exit 1; }

echo "==> Fetching bootstrap compiler"
curl -fL -o "$work/frege/fregec.jar" "$BOOTSTRAP_JAR_URL"

echo "==> Building (make all) — 3-stage self-hosting bootstrap"
( cd "$work/frege" && make all )

mkdir -p "$repo_root/libs"
cp "$work/frege/fregec.jar" "$dest"
echo "==> Wrote $dest"
java -jar "$dest" -version || true
echo "==> Done. Commit hash pinned: $FREGE_COMMIT"
